---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - image: k8s.gcr.io/busybox
      name: busybox
      command: [ "sh", "-c"]
      args:
      - 'echo $MY_ENV_VAR'
      env:
        - name: 'MY_ENV_VAR'
          valueFrom:
            secretKeyRef:
             name: my-secret
             key: MESSAGE
  restartPolicy: Never