apiVersion: batch/v1
kind: Job
metadata:
  name: sleep
spec:
  completions: 6
  parallelism: 2
  template:
    metadata:
      name: sleep
    spec:
      containers:
      - name: sleep
        image: k8s.gcr.io/busybox
        command: ["sleep",  "20"]
      restartPolicy: Never